remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
title: Nidheesh V
description: Researcher | Mechanical Engineer
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

github:
  orcid_url: https://orcid.org/0009-0009-9513-2623
  linkedin_url: https://in.linkedin.com/in/nidheesh-virakante
  mrl_url: https://www.me.iitb.ac.in/~a_jain/


